#ifndef TEXTSERVICE_GLOBAL_H
#define TEXTSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTSERVICE_LIBRARY)
#  define TEXTSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEXTSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTSERVICE_GLOBAL_H
