#ifndef DEFAULTCOMPOSER_GLOBAL_H
#define DEFAULTCOMPOSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEFAULTCOMPOSER_LIBRARY)
#  define DEFAULTCOMPOSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEFAULTCOMPOSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEFAULTCOMPOSER_GLOBAL_H
